# Nome do workflow (aparecerá na aba Actions)
name: CI Simples

# Eventos que disparam o workflow
on:
  push:
    branches: [dev] # dispara quando há commit na branch dev
  pull_request:
    branches: [dev] # dispara quando há PR para dev

jobs:
  # Definindo um job chamado "build"
  build:
    runs-on: ubuntu-latest # máquina Linux usada pelo GitHub

    steps:
      # 1. Baixar o código do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4
